### ISSUE TITLE
loadUrl返回的数据是数组，该如何处理？

### ISSUE THREAD

**Issue by or0or1** [fallsea/fsLayuiPlugin#1]
@FALLSEA 

我的表单使用了你的插件，赞一个，挺好用的。

但我遇到一个问题。希望在线的时候解答一下疑惑。 谢谢

需求是： 
	点击表格的编辑，弹窗编辑。（和datagrid的编辑类似，不同的是数据）
         使用你的插件，是通过loadUrl获得数据，然后把数据插入edit.html，进行显示。
	 但我通过loadUrl得到数据格式是数组：
		 [{“host”:”test1”,”city”:”guangdong”},{“host”:”test2”,”city”:”guangdong”}]
                 数组的长度是不定的。

疑问：
	实现这样的需要，我以前的做法是先取数据，然后使用模版返回一个有数据的 edit.html

	使用了你这个插件，我就不知道怎么处理了。 edit.html 支持写for 循环来动态处理？ how ？ 

       谢谢！

**Comment by fallsea** [comment]
编辑信息，不应该是只有一条数据吗？为什么你这里会是一个list的结果集？最好有一些截图可以看下你的场景

**Comment by or0or1** [comment]
数据表格每一行，就是一条记录，但记录中的某一个字段，存放的是json格式的数据，在编辑的时候，我需要把json的数据展现出来。

json数据格式有： {"lw2112":"100"}、  {"bs230":80,"bs231":20}、{"A":{"bs230":80,"bs231":20}, "B":{"bs231":80,"bs232":20}}

对于第二种，返回给edit.html的数据, 我处理成数组形式的:  [{"host":"bs230","ratio":80},{"host":"bs231","ratio":20}]

**Comment by fallsea** [comment]
新增的时候，这些json数据是怎么来的呢？截图看下新增和编辑页面

**Comment by fallsea** [comment]
我创建一个群，加一下 24017956

**Comment by or0or1** [comment]
ok
