### ISSUE TITLE
在flask下创建项目 报项目文件找不到

### ISSUE THREAD

**Issue by yisake** [fallsea/fsLayuiPlugin#2]
GET http://127.0.0.1:5000/plugins/frame/js/fsForm.js?v=1.6.0  

代码如下：
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html;charset=UTF-8"/>
    <title>fsLayuiPlugin</title>
    <meta name="keywords" content="fsLayuiPlugin,layui,layuiPlugin,layui插件" />
    <meta name="description" content="fsLayuiPlugin,layui,layuiPlugin,layui插件" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta http-equiv ="Pragma" content = "no-cache"/>
    <meta http-equiv="Cache-Control" content="no cache" />
    <meta http-equiv="Expires" content="0" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="format-detection" content="telephone=no"/>
    <link rel="stylesheet" type="text/css" href="/plugins/layui/css/layui.css" media="all"/>
    <link rel="stylesheet" type="text/css" href="/css/fs.css" media="all"/>
    <script type="text/javascript" src="/plugins/layui/layui.js"></script>
    <script type="text/javascript" src="/plugins/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/plugins/frame/js/fsDict.js?v=1.4.1"></script>
    <script type="text/javascript" src="/plugins/frame/js/fs.js?v=1.4.1"></script>
    <script type="text/javascript" src="/plugins/frame/js/frame.js?v=1.4.1"></script>
  </head>
  <body class="layui-layout-body">
    <div class="layui-fluid">
      <form class="layui-form">
        <div class="layui-form-item">
          <label class="layui-form-label">名称</label>
          <div class="layui-input-block">
            <input type="text" name="name" required="" lay-verType="tips" lay-verify="required" placeholder="请输入名称" autocomplete="off" class="layui-input"/>
          </div>
        </div>
        <div class="layui-form-item">
          <label class="layui-form-label">类型</label>
          <div class="layui-input-block">
            <input type="checkbox" name="type" title="写作" value="write">
            <input type="checkbox" name="type" title="阅读" value="read">
            <input type="checkbox" name="type" title="发呆" value="dai">
          </div>
        </div>
        <div class="layui-form-item">
          <label class="layui-form-label">性别</label>
          <div class="layui-input-inline">
            <input type="radio" name="sex" value="男" title="男" checked="checked">
            <input type="radio" name="sex" value="女" title="女">
          </div>
          <label class="layui-form-label">状态</label>
          <div class="layui-input-inline">
            <input type="checkbox" name="state" lay-skin="switch" lay-text="开启|关闭" value="1" checked>
          </div>
        </div>
        <div class="layui-form-item">
          <label class="layui-form-label">城市</label>
          <div class="layui-input-inline">
            <select name="city" lay-verify="required"  lay-verType="tips" class="fsSelect" dict="city" addNull="1">
            </select>
          </div>
          <label class="layui-form-label">创建时间</label>
          <div class="layui-input-inline">
            <input type="text" name="createdTime" autocomplete="off" class="layui-input fsDate" dateType="datetime" />
          </div>
        </div>
        <div class="layui-form-item">
          <label class="layui-form-label">省份</label>
          <div class="layui-input-inline" style="width: 100px;">
            <select id="area2222222" name="area1" lay-filter="xxxxxx1" class="fsSelect" dict="area1" addNull="1" childrenSelectId="xxxxxx2">
            </select>
          </div>
          <label class="layui-form-label">城市</label>
          <div class="layui-input-inline" style="width: 100px;">
            <select id="xxxxxx2" name="area2" lay-filter="xxxxxx2" class="fsSelect" isLoad="0" dict="area2" addNull="1" childrenSelectId="xxxxxx3">
            </select>
          </div>
          <label class="layui-form-label">区</label>
          <div class="layui-input-inline" style="width: 100px;">
            <select id="xxxxxx3" name="area3" class="fsSelect" isLoad="0" dict="area3" addNull="1">
            </select>
          </div>
        </div>
        <div class="layui-form-item layui-form-text">
          <label class="layui-form-label">附件</label>
          <div class="layui-input-inline">
            <input type="text" id="filePath" name="filePath" autocomplete="off" disabled="disabled" class="layui-input"/>
          </div>
          <div class="layui-input-inline">
            <button type="button"  class="layui-btn" function="upload" fileElem="#filePath" fileAccept="file" fileExts="" fileSize="1024" inputs="type:test">上传图片</button>
          </div>
        </div>
        <div class="layui-form-item layui-form-text">
          <label class="layui-form-label">描述</label>
          <div class="layui-input-block">
            <textarea id="description" name="description" placeholder="请输入描述" class="fsLayedit" height="80"></textarea>
          </div>
        </div>
        <hr/>
        <div class="layui-form-item" style="text-align: center;">
          <button class="layui-btn" lay-submit="" lay-filter="save" url="/fsbus/1001">新增</button>
          <button type="button" class="layui-btn layui-btn-primary" function="close">关闭</button>
        </div>
      </form>
    </div>
  </body>
</html>

n.use @ layui.js:2
(anonymous) @ frame.js:8

这里貌似用了/plugins/的路径。。。不知道怎么回事 改改吧

**Comment by fallsea** [comment]
代码描述不清晰，最好提供截图，还有怎么操作的

**Comment by yisake** [comment]
是我没有配置fs.js 我close掉。。

**Comment by yisake** [comment]
@fallsea  问个题外的问题 flask里面 像<a href="./xx/file.html"> 这个路径应该怎么写啊？
